#ifndef LEDSSTATESCHANGE_H
#define LEDSSTATESCHANGE_H

#define BAUDRATE 115200
#define SERIAL_PORT_CONFIGS SERIAL_8N1

#define BUTTON_PIN_NUMBER 4
#define LED_1_PIN_NUMBER 22
#define LED_2_PIN_NUMBER 23

#define STARTS_CHARACTERS "$$"
#define SEPERATOR_CHARACTERS ","
#define END_CHARACTERS "**"
#define PIN_HIGH_CHARACTERS "On"
#define PIN_LOW_CHARACTERS "Off"

#define DEBOUNCE_DELAY_TIME_MS 250

#define FIRST_SYSTEM_STATE 3
#define END_SYSTEM_STATE 0

#define LEN_ULONG_MAX_TO_STR 10

#define SYSTEM_CHANGE_EDGE_TRIGGERING RISING

#define INITIAL_SYSTEM_STATE 3

#endif