Serial Port Driver: Main
Main
Files
file main.cpp
This file is main file.
Functions
void printSerialFailCode (SerialFailCodeType &failCode)
This function prints the SerialComm class fail code.
void printMqttFailCode (MqttFailCodeType &failCode)
This function prints the MqttComm class fail code.
void printIniParserFailCode (IniParserFailCode &failCode)
This function prints the IniParser class fail code.
int main ()
This function is main function of programme.
Detailed Description
Author
Bilge Kağan ÖZKAN
Function Documentation
main()
int main ()
#include <app/main.cpp>
This function is main function of programme.
Parameters
N/A
Returns
N/A
Definition at line 118 of file main.cpp.
            {
     SerialComm serialComm;
     MqttComm mqtt;
     IniParser iniParser;
     Message message;
     IniParserSerialPortConfig serialPortConfigData;
     IniParserMqttClientConfig mqttClientConfigData;
     IniParserMessageConfig messageConfigData;
     try
     {
         iniParser.startParsing();
         serialPortConfigData = iniParser.getSerialPortConfigData();
         mqttClientConfigData = iniParser.getMqttClientConfigData();
         messageConfigData = iniParser.getMessageConfigData();
         serialComm.startCommunication(serialPortConfigData, mqtt);
         mqtt.connectServer(mqttClientConfigData);
         message.createMessageFormat(messageConfigData);
         while (true) {
             serialComm.readDataFromSerial(message);
             mqtt.publishMessage(message);
         }
     }
     catch(const std::exception& e)
     {
         std::cout << "Unexpected error occured!!!" << std::endl;
         std::cout << e.what() << std::endl;
         return -1;
     }
     catch(FailCode<SerialFailCodeType>& failCode)
     {
         printSerialFailCode(failCode.getValue());
         return -1;
     }
     catch(FailCode<MqttFailCodeType>& failCode)
     {
         printMqttFailCode(failCode.getValue());
         return -1;
     }
     catch(FailCode<IniParserFailCode>& failCode)
     {
         printIniParserFailCode(failCode.getValue());
         return -1;
     }
     catch(...)
     {
         std::cout << "unexpected and undefined error occured" << std::endl;
         return -1;
     }
     return 0;
 }
References MqttComm::connectServer(), Message::createMessageFormat(), IniParser::getMessageConfigData(), IniParser::getMqttClientConfigData(), IniParser::getSerialPortConfigData(), FailCode< T >::getValue(), printIniParserFailCode(), printMqttFailCode(), printSerialFailCode(), MqttComm::publishMessage(), SerialComm::readDataFromSerial(), SerialComm::startCommunication(), and IniParser::startParsing().
printIniParserFailCode()
void printIniParserFailCode (IniParserFailCode & failCode)
#include <app/main.cpp>
This function prints the IniParser class fail code.
Parameters
[in] failCode IniParserFailCode reference.
Returns
N/A
Definition at line 93 of file main.cpp.
 {
     switch (failCode)
     {
     case INIPARSER_INI_FILE_COULD_NOT_OPENED:
         std::cout << "ERROR: The  config.ini file can not opened!!!" << std::endl;
         std::cout << "Please check the config/config.ini path";
         break;
     case INIPARSER_PARSING_ERROR:
         std::cout << "ERROR: An convertation error occured.!!!" << std::endl;
         std::cout << "Please check contents of the config.ini file";
         break;
     default:
         std::cout << "ERROR: " << failCode;
         break;
     }
     std::cout << std::endl << "The program is closing..." << std::endl;
 }
References INIPARSER_INI_FILE_COULD_NOT_OPENED, and INIPARSER_PARSING_ERROR.
Referenced by main().
printMqttFailCode()
void printMqttFailCode (MqttFailCodeType & failCode)
#include <app/main.cpp>
This function prints the MqttComm class fail code.
Parameters
[in] failCode MqttFailCodeType reference.
Returns
N/A
Definition at line 69 of file main.cpp.
 {
     switch (failCode)
     {
     case MQTT_CONNECTION_ERROR:
         std::cout << "ERROR: An connection error occured.!!!" << std::endl;
         std::cout << "Please check server ip, port, username and password in the config.ini file and your internet connection";
         break;
     case MQTT_QOS_IS_INVALID:
         std::cout << "ERROR: QOS is invalid!!!" << std::endl;
         std::cout << "Please check the config.ini file";
     default:
         std::cout << "ERROR: " << failCode;
         break;
     }
     std::cout << std::endl << "The program is closing..." << std::endl;
 }
References MQTT_CONNECTION_ERROR, and MQTT_QOS_IS_INVALID.
Referenced by main().
printSerialFailCode()
void printSerialFailCode (SerialFailCodeType & failCode)
#include <app/main.cpp>
This function prints the SerialComm class fail code.
Parameters
[in] failCode SerialFailCodeType reference.
Returns
N/A
Definition at line 23 of file main.cpp.
 {
     switch (failCode)
     {
     case SERIALPORT_BAUDRATE_OUT_OF_RANGE:
         std::cout << "ERROR: The baudrate is out of range!!!" << std::endl;
         std::cout << "Please check the config.ini file";
         break;
     case SERIALPORT_DATABIT_OUT_OF_RANGE:
         std::cout << "ERROR: The data bit is out of range!!!" << std::endl;
         std::cout << "Please check the config.ini file";
         break;
     case SERIALPORT_PARITYBIT_OUT_OF_RANGE:
         std::cout << "ERROR: The parity bit is out of range!!!" << std::endl;
         std::cout << "Please check the config.ini file";
         break;
     case SERIALPORT_STOPBIT_OUT_OF_RANGE:
         std::cout << "ERROR: The stop bit is out of range!!!" << std::endl;
         std::cout << "Please check the config.ini file";
         break;
     case SERIALPORT_PORTNAME_IS_NONE:
         std::cout << "ERROR: Serial Port name is NONE!!!" << std::endl;
         std::cout << "Please check the config.ini file";
         break;
     case SERIALPORT_READING_ERROR:
         std::cout << "ERROR: An error occured while reading from serial port!!!";
         break;
     case SERIALPORT_COULD_NOT_OPENED:
         std::cout << "ERROR: The serial port was not opened!!!";
         break;
     case SERIALPORT_COULD_NOT_CLOSED:
         std::cout << "ERROR: The serial port was not opened!!!";
         break;
     default:
         std::cout << "ERROR: " << failCode;
         break;
     }
     std::cout << std::endl << "The program is closing..." << std::endl;
 }
References SERIALPORT_BAUDRATE_OUT_OF_RANGE, SERIALPORT_COULD_NOT_CLOSED, SERIALPORT_COULD_NOT_OPENED, SERIALPORT_DATABIT_OUT_OF_RANGE, SERIALPORT_PARITYBIT_OUT_OF_RANGE, SERIALPORT_PORTNAME_IS_NONE, SERIALPORT_READING_ERROR, and SERIALPORT_STOPBIT_OUT_OF_RANGE.
Referenced by main().