Serial Port Driver: IniParser Class Reference
IniParser Class Reference
IniParser
IniParser class reads the "config.ini" file and parses to create Serial Port Config Data, MQTT Client Config Data and Message Config Data, which types are respectively IniParserSerialPortConfig, IniParserMqttClientConfig and IniParserMessageConfig enum.
#include <IniParser.h>
Public Member Functions
IniParser ()
This constructor initializes the failCode object.
~IniParser ()=default
This is default destructor.
void startParsing ()
This function starts the reading and parsing processes.
IniParserSerialPortConfig & getSerialPortConfigData ()
This function returns the Serial Port Config Data.
IniParserMqttClientConfig & getMqttClientConfigData ()
This function returns the MQTT Client Config Data.
IniParserMessageConfig & getMessageConfigData ()
This function returns the Message Config Data.
Private Attributes
FailCode< IniParserFailCode > failCode
This variable keeps objectified FailCode class with IniParserFailCode enum.
IniParserSerialPortConfig serialPortConfig
This variable keeps Serial Port Config Data.
IniParserMqttClientConfig mqttClientConfig
This variable keeps MQTT Client Config Data.
IniParserMessageConfig messageConfig
This variable keeps Message Config Data.
Detailed Description
IniParser class reads the "config.ini" file and parses to create Serial Port Config Data, MQTT Client Config Data and Message Config Data, which types are respectively IniParserSerialPortConfig, IniParserMqttClientConfig and IniParserMessageConfig enum.
Definition at line 25 of file IniParser.h.
Constructor & Destructor Documentation
IniParser()
IniParser::IniParser ()
This constructor initializes the failCode object.
Parameters
N/A
Returns
N/A
Definition at line 16 of file IniParser.cpp.
 {
     failCode = INIPARSER_OK;
 }
References failCode, and INIPARSER_OK.
~IniParser()
IniParser::~IniParser () default
This is default destructor.
Parameters
N/A
Returns
N/A
Member Function Documentation
getMessageConfigData()
IniParserMessageConfig & IniParser::getMessageConfigData ()
This function returns the Message Config Data.
Parameters
N/A
Returns
IniParserMessageConfig reference.
Definition at line 97 of file IniParser.cpp.
 {
     return messageConfig;
 }
References messageConfig.
Referenced by main().
getMqttClientConfigData()
IniParserMqttClientConfig & IniParser::getMqttClientConfigData ()
This function returns the MQTT Client Config Data.
Parameters
N/A
Returns
IniParserMqttClientConfig reference.
Definition at line 87 of file IniParser.cpp.
 {
     return mqttClientConfig;
 }
References mqttClientConfig.
Referenced by main().
getSerialPortConfigData()
IniParserSerialPortConfig & IniParser::getSerialPortConfigData ()
This function returns the Serial Port Config Data.
Parameters
N/A
Returns
IniParserSerialPortConfig reference.
Definition at line 77 of file IniParser.cpp.
 {
     return serialPortConfig;
 }
References serialPortConfig.
Referenced by main().
startParsing()
void IniParser::startParsing ()
This function starts the reading and parsing processes.
Parameters
N/A
Returns
throw INIPARSER_INI_FILE_COULD_NOT_OPENED: if config.ini file can not open. throw INIPARSER_PARSING_ERROR: if the content of config.ini file is wrong.
Definition at line 27 of file IniParser.cpp.
 {
     boost::property_tree::ptree pt;
     try
     {
         boost::property_tree::ini_parser::read_ini("./config/config.ini", pt);
     }
     catch(const boost::wrapexcept<boost::property_tree::ini_parser::ini_parser_error>& e)
     {
         FAILCODE_SET_AND_EXIT(failCode, INIPARSER_INI_FILE_COULD_NOT_OPENED);
     }
     try
     {
         serialPortConfig.portName = pt.get<std::string>("SerialConfig.SC_PORT_NAME");
         serialPortConfig.baudRate = pt.get<int>("SerialConfig.SC_BAUDRATE");
         serialPortConfig.dataBit = pt.get<int>("SerialConfig.SC_DATABIT");
         serialPortConfig.stopBit = pt.get<int>("SerialConfig.SC_STOPBIT");
         serialPortConfig.parityBit = pt.get<std::string>("SerialConfig.SC_PARITYBIT");
         mqttClientConfig.serverAdress = pt.get<std::string>("MqttConfig.MQTT_ADDRESS");
         mqttClientConfig.port = pt.get<int>("MqttConfig.MQTT_PORT");
         mqttClientConfig.username = pt.get<std::string>("MqttConfig.MQTT_USERNAME");
         mqttClientConfig.password = pt.get<std::string>("MqttConfig.MQTT_PASSWORD");
         mqttClientConfig.topic1 = pt.get<std::string>("MqttConfig.MQTT_TOPIC_1");
         mqttClientConfig.topic2 = pt.get<std::string>("MqttConfig.MQTT_TOPIC_2");
         mqttClientConfig.topic3 = pt.get<std::string>("MqttConfig.MQTT_TOPIC_3");
         mqttClientConfig.topic4 = pt.get<std::string>("MqttConfig.MQTT_TOPIC_4");
         mqttClientConfig.qos = pt.get<int>("MqttConfig.MQTT_QOS");
         int randomValue = std::rand();
         mqttClientConfig.id = "mqtt_publisher_" + std::to_string(randomValue);
         messageConfig.startCharacters = pt.get<std::string>("MessageFormat.MF_START_CHARACTERS");
         messageConfig.seperatorCharacters = pt.get<std::string>("MessageFormat.MF_SEPERATOR_CHARACTERS");
         messageConfig.endCharacters = pt.get<std::string>("MessageFormat.MF_END_CHARACTERS");
         messageConfig.seperatedDataCount = pt.get<int>("MessageFormat.MF_SEPERATED_DATA_COUNT");
     }
     catch(const boost::wrapexcept<boost::property_tree::ptree_bad_data>& e)
     {
         FAILCODE_SET_AND_EXIT(failCode, INIPARSER_PARSING_ERROR);
     }
 }
References IniParserSerialPortConfig::baudRate, IniParserSerialPortConfig::dataBit, IniParserMessageConfig::endCharacters, failCode, FAILCODE_SET_AND_EXIT(), IniParserMqttClientConfig::id, INIPARSER_INI_FILE_COULD_NOT_OPENED, INIPARSER_PARSING_ERROR, messageConfig, mqttClientConfig, IniParserSerialPortConfig::parityBit, IniParserMqttClientConfig::password, IniParserMqttClientConfig::port, IniParserSerialPortConfig::portName, IniParserMqttClientConfig::qos, IniParserMessageConfig::seperatedDataCount, IniParserMessageConfig::seperatorCharacters, serialPortConfig, IniParserMqttClientConfig::serverAdress, IniParserMessageConfig::startCharacters, IniParserSerialPortConfig::stopBit, IniParserMqttClientConfig::topic1, IniParserMqttClientConfig::topic2, IniParserMqttClientConfig::topic3, IniParserMqttClientConfig::topic4, and IniParserMqttClientConfig::username.
Referenced by main().
Member Data Documentation
failCode
FailCode<IniParserFailCode> IniParser::failCode private
This variable keeps objectified FailCode class with IniParserFailCode enum.
Definition at line 28 of file IniParser.h.
Referenced by IniParser(), and startParsing().
messageConfig
IniParserMessageConfig IniParser::messageConfig private
This variable keeps Message Config Data.
Definition at line 31 of file IniParser.h.
Referenced by getMessageConfigData(), and startParsing().
mqttClientConfig
IniParserMqttClientConfig IniParser::mqttClientConfig private
This variable keeps MQTT Client Config Data.
Definition at line 30 of file IniParser.h.
Referenced by getMqttClientConfigData(), and startParsing().
serialPortConfig
IniParserSerialPortConfig IniParser::serialPortConfig private
This variable keeps Serial Port Config Data.
Definition at line 29 of file IniParser.h.
Referenced by getSerialPortConfigData(), and startParsing().
The documentation for this class was generated from the following files:
lib/iniparser/IniParser.h
src/IniParser.cpp